### ISSUE TITLE
Have donation button on the web site

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1281]
_From [kingi89](https://code.google.com/u/101706443478653595036/) on January 12, 2011 12:48:38_

I found Clementine to be my new favourite music player, and to show my appreciation, I'd have liked to show my support by donating. However, Clementine's web site does not have any kind of donation button or any donation info whatsoever.

I understand that there could be some issues with local laws (at least in Finland it is illegal to ask for donations without fundraising permit). If that is the case, it could be worked around by selling backgrounds or something like that.

I am pretty sure that there are more people like me, and I think the developers wouldn't mind some extra money.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1281_

**Comment by Betree** [comment]
Hi Clementine maintainers, this is a very humble position that you have here :+1: Maybe your position since 2011 has changed, getting donations may be a way to give back to contributors to incentive developers to participate. I'll be happy to give too so I've created a pledge on https://opencollective.com/clementine.
