### ISSUE TITLE
Tags not updated when modified by another program

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1330]
_From [igorek.rnd](https://code.google.com/u/103137053131610477715/) on January 19, 2011 22:47:09_

When you change the mp3 tag files by another program, such as EasyTag, the collection is not updated either manually or automatically. In this case we need to move files with changed tags to the collection refreshed.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1330_

**Comment by wks** [comment]
I would like to re-open this issue.

In the latest version (1.3.1), there is a menu item "Do a full library rescan" and it works for libraries. However, I do not use the library, but create playlists directly from the "files" view.

In v1.3.1, if the ID3 metadata of a MP3 file is changed externally by another program, the item in the Clementine playlist is not updated, and will not be updated if I play that song or re-open Clementine.

**Steps to reproduce**:
1. Add a mp3 file to a Clementine playlist. It shows its title, artist and album.
2. Change the metadata in another program (such as VLC, or my command line script)
3. Try to play the file in Clementine
4. Try to use the "Do a full library rescan"

**Actual result**
* The metadata shown in Clementine playlist remains what it was before the change.
* But if I inspect the item by right-click on the playlist and select "Edit track information...", it shows the updated info.

**Expected result**
* As soon as the mp3 file is played, the information (title, artist, album) in the playlist should be updated.

A workaround is to remove that playlist item and add it back again. But it is very tedious because my script may update many items at the same time.

Issue #784 and #1478 is about files in the library, and it has a solution now. But playlist items still cannot be refreshed. So this issue is no longer a duplicate of #784.

I think there should be an explicit "refresh" menu item for the playlist. Alternatively the metadata can be re-loaded when a file is played.

There are two related issue #3204 and #5420: when the song is not available in the filesystem or the Internet stream source is inaccessible, the playlist should still retain the metadata it has last seen.
