### ISSUE TITLE
Integrate Clementine with Setpoint for Logitech Keyboards

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2431]
_From [zeppelin...@gmail.com](https://code.google.com/u/103997924569130443478/) on November 27, 2011 21:06:55_

I have recently purchased the Logitech K800 Wireless Keyboard.  This keyboard has media buttons and uses a program called Logitech Setpoint to assign the keys.  Unfortunately, setpoint does not recognize Clementine as a media player therefore I can not get the media buttons to work.  I was hoping there was a way to get Clementine to be noticed as a media player in Setpoint.  I did find this topic stating how to add programs to setpoint but I have no idea how to add Clementine: http://www.hydrogenaudio.org/forums/index.php?showtopic=30246

**Attachment:** [Capture.PNG Selection_001.png](http://code.google.com/p/clementine-player/issues/detail?id=2431)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2431_

**Comment by PlanetLotus** [comment]
Thank you so much! This was keeping Clementine from being my favorite media player. Now there's no contest.

For future readers, it's worth noting that I had to reboot my machine for this to start working. I probably just didn't restart the correct process but at any rate it was all working fine after rebooting.

Also, I recommend launching your text editor in Administrator mode so that you can actually save the file when you're done (otherwise Notepad++ complains that other processes are using the file). I ended up saving the file to desktop and then replacing the file through Windows, but I think running Notepad++ as Administrator would've worked too.
