### ISSUE TITLE
"Clear Playlist on exit" option

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2465]
_From [geoffrey...@gmail.com](https://code.google.com/u/114861209313549454022/) on December 05, 2011 06:01:16_

The addition of a "Clear Playlist on Exit" option would be great.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2465_

**Comment by JohnMcHugh** [comment]
I was looking to see if it was possible to set up Clementine so that the playlist would clear on exit when I came across this issue.  I understand the rationale of the rejection, but want to make a counter argument. 

 I was looking for a very simple music player, something that I can give a predefined playlist to, play the contents, and stop.  Think of this as the equivalent of the old fashioned turntable with the tone arm that returned and stopped the turntable at the end of the record. Clementine comes close, but the retention of the playlist from the previous use tends to confuse other members of the household.

I have my music organized into playlists, some for whole albums, others for classical works, a symphony or an opera and they are indexed by works, composers, performers, etc.  I don't need my "record player" to organize them, modify them, etc.  All it really needs to do is play them and stop.
