### ISSUE TITLE
Youtube support

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2626]
_From [svndepoo...@gmail.com](https://code.google.com/u/115612225465938014081/) on January 17, 2012 23:43:24_

Support for youtube playback (only sound) trough Clementine would be nice. (like http://flavio.tordini.org/musictube ).

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2626_

**Comment by samarth-math** [comment]
Or maybe a youtube login and red integration if for playing without video?

**Comment by pabru** [comment]
Youtube-dl already allows access without the proprietary YouTube API, so this could be technically a possibility.

**Comment by arman19940326** [comment]
Unofficial Google Play Music desktop app now supports YouTube Music. It would be uber cool if Clementine adds support for YouTube Music too.
( https://www.xda-developers.com/unofficial-youtube-music-desktop-app/ )

**Comment by toramanlis** [comment]
> The TOS are: "you agree not to access Content through any technology or means other than the video playback pages of the Website itself, the YouTube Player, or such other means as YouTube may explicitly designate for this purpose;"

if you can access the content via firefox, you should be able to access it via clementine. while still using the youtube website.

say clementine includes a browser to it's features. it loads only one local web page which has nothing else but an embeded youtube video. you can change which video is embeded by clementine's own gui. you will still be accessing the youtube content through their web application. regardless of which of these details fail, I'm pretty sure you are allowed to load youtube to your browser, since all browsers can be minimized, clementine could do it to it's own browser probably because it could very well be a taskbar also and all the other task bars are allowed to do so.

**Comment by larinius** [comment]
Aimp on Windows plays all YouTube music perfectly fine with the highest quality among free music services - YouTube audio has 320 kb and even better vs 120 on other free platforms. 

Argument that YouTube just for watching videos is absurd. Chill Cow music streams have millions listeners.

Clementine developers can fight with users, arguing that feature is not needed or against TOS or can solve user request as Aimp devs did.

**Comment by Jarfeh** [comment]
> Aimp on Windows plays all YouTube music perfectly fine with the highest quality among free music services - YouTube audio has 320 kb and even better vs 120 on other free platforms.
> 
> Argument that YouTube just for watching videos is absurd. Chill Cow music streams have millions listeners.
> 
> Clementine developers can fight with users, arguing that feature is not needed or against TOS or can solve user request as Aimp devs did.

Similar to Aimp, foobar2000 can also playback youtube tracks. Although foobar2000 utilizes a third party plugin to do so.
