### ISSUE TITLE
Remember original playlist extension when resaving the playlist

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2951]
_From [spiffyt...@gmail.com](https://code.google.com/u/111798131081781904371/) on May 24, 2012 23:07:33_

If I create a .m3u playlist, then hit the 'save' button, I'm prompted for a new filename, and the save dialog defaults to the .xspf extension. If I'm not paying attention I wind up with both types of playlist and later get confused as to which I actually want. 

Please make it so that the dialog defaults to whatever filetype the playlist was last saved as.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2951_

**Comment by weinimo** [comment]
I would really appreciate if you could implement this feature. The current behavior when saving a loaded playlist is very annoying. Every time I save I have to fix the filename manually.

**Comment by gsantner** [comment]
+1

**Comment by gsantner** [comment]
Thanks for your quick response (+ implementation)! :)

Am 7. Juni 2016 19:05:20 MESZ, schrieb John Maguire <notifications@github.com>:

Closed #2951<https://github.com/clementine-player/Clementine/issues/2951> via fde64e3<https://github.com/clementine-player/Clementine/commit/fde64e31b8b7016050512c46c551b5098821fb27>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/clementine-player/Clementine/issues/2951#event-684669370>, or mute the thread<https://github.com/notifications/unsubscribe/AGbHInOGMjTa2dCMX6__8Grk360qlC6nks5qJaTQgaJpZM4BTUUF>.

------
Kind regards,
Gregor Santner
https://github.com/de-live-gdev
