### ISSUE TITLE
Smart Playlists by File Path

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3650]
_From [rfstro...@gmail.com](https://code.google.com/u/112855085857406522957/) on May 01, 2013 20:33:33_

I pre-organize my music in genre folders on my hard drive. Most of the time, I just want to play random files from a specific folder (and its sub-folders) and I want that list to update automatically when I download new files.

In WinAmp, I can create a smart playlist for this, by specifying the search term "file path" + "begins with".

This doesn't seem to be available in Clementine. The option "file name" only considers the actual file name, but not the path.

Thanks!

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3650_

**Comment by octoquad** [comment]
This used to work in 1.1 if I recall correctly, as I still have smart playlists configured by path using the Search terms _File name contains /path/to/music/a_. Unfortunately this doesn't work at all since then and playlists are rendered empty.

If I use the the search terms _File name contains **a**_ nothing is found across multiple folders, which is a bit strange. Perhaps this specific filter is broken with Clementine > 1.1? I'm currently using 1.3.1 on Ubuntu GNOME 16.04.

I have also attempted the following:
- Deleting and recreating the smart playlists
- Removing paths from Preferences > Music Library and then re-adding
- Deleted the clementine database
- Completely removed all clementine related files in the /home/user directory

Perhaps two new search terms could be:

- _File Path **is** {list from Preferences > Music Library}_ and
- _File Path **contains** /some/other/location_ for music that was added outside the normal directories defined by Preferences > Music Library.
