### ISSUE TITLE
Clear playlist button too close to the playback buttons

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3752]
_From [98metab...@gmail.com](https://code.google.com/u/113659874736185568443/) on June 24, 2013 09:34:32_

I would appreciate little bigger playback buttons, and especially the ability to put clear playlist button somewere else, to avoid deleting a playlist inadvertently.
Thank you very much :-)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3752_

**Comment by rolandixor** [comment]
I just ran into this same issue, although to my knowledge I **DID NOT** click the clear playlist button. The undo button is inactive, and my playlist that I spent weeks working on is empty.

Is there no way to recover a backup?

**Comment by v-fox** [comment]
Annnnnd, so am I. Usually, there is "undo" action but today there wasn't and I lost my "favourite" playlist that I've been compiling for years from my >100GB music collection >_< Good thing there were recent manual backups.

And that moronic menu entry being there isn't even the worst of it. At least on Linux a very fast right mouse click also acts as "activation-on-release". So on press context menu is triggered and on release the menu entry that happens to be under the cursor triggers. It can be so fast that the menu can activate before or instead of being rendered on screen ! So just accidentally clicking while casually moving mouse around can trigger it without you even being aware.

This s literally the worst thing about Clementine. Second being it's database hangs and the third - bitrot, such as being stuck on dead Qt4.

**Comment by rolandixor** [comment]
Fix it... I just did the same thing again, and there is no way to undo!

**Comment by rolandixor** [comment]
> _From [davidsansome](https://code.google.com/u/davidsansome/) on June 24, 2013 01:32:50_
> 
> There was some discussion about the position of the clear playlist button ages ago in issue 389 . The decision was it's commonly used enough to be at the bottom, and it looks better there anyway. You can even undo clearing the playlist now, so it shouldn't be quite as bad when you click it accidentally.
> 
> **Status:** WontFix

This is a lie. **YOU CANNOT** undo.

**Comment by chaoscommander** [comment]
Crickets...
