### ISSUE TITLE
Multiple instances of 'clementine-tagreader.exe'

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3972]
_From [waffoc...@gmail.com](https://code.google.com/u/111695324319934827590/) on November 20, 2013 07:50:27_

Upon launching Clementine, it also launches a whole slew of 
'clementine-tagreader' processes. Eight to be precise.
Additionally, a corresponding number of conhosts.

This has been happening since hourly build 1.0-108-g12daf6b,
however at that point there were "only" two tagreader executables running simultaneously.
Since 1.1.1-193-g7058d23 it has increased to EIGHT(8).

Surely this isn't working as intended.

All this in contrast to anything prior to 1.0-108-g12daf6b, where there were no discernible tagreader executables running in tandem.

This is on Windows 7 64bit, and reproduced on multiple machines.

**Attachment:** [2013-11-20_07-12-12.png](http://code.google.com/p/clementine-player/issues/detail?id=3972)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3972_

**Comment by vatterspun** [comment]
I'm not seeing eight instances any longer (as with the last time I tested) but I am seeing two.  Is this expected behavior?

![2017-02-27 20_48_50-windows task manager](https://cloud.githubusercontent.com/assets/1289134/23389592/9002485c-fd2e-11e6-8316-cf6b23825dc0.png)

**Setup**: Win7x86 ; Version 1.3.1-287-g652f38a ; running the portable version and playing some subscription DI.FM music.
