### ISSUE TITLE
organize file dialog: track number should have leading zero

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#438]
_From [solomonov.v](https://code.google.com/u/113480730809990041289/) on June 25, 2010 11:09:40_

What steps will reproduce the problem? 1. Open organize files dialog
2. File naming scheme should contain "&#37;track"
3. Organize files

In case file naming scheme is "&#37;extension/&#37;artist/&#37;album {&#37;disc}{(&#37;year)}/&#37;track. &#37;artist - &#37;title.&#37;extension"
What is the expected output?
/var/ftp/Music/mp3/Luomo/Vocalcity (2000)/05. Luomo - Tessio.mp3

What do you see instead?
/var/ftp/Music/mp3/Luomo/Vocalcity (2000)/5. Luomo - Tessio.mp3 What version of the product are you using? On what operating system? r1343 , Gentoo x86, clementine-9999.ebuild from gentoo-multimedia overlay Please provide any additional information below. I think that leading zeros can help when browsing files with file manager or command line.

Thanks for all work you have done, I was waiting for this feature.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=438_

**Comment by blakejriley** [comment]
This issue was last updated with the status "Leading zeroes added", but there are no leading zeroes when ripping CDs with Clementine 1.2.3. Was this feature later removed?

Unfortunately I can't find any kind of documentation for Clementine to see whether it's possible to enable this feature via special syntax in the "File Format" field of the "Rip CD" menu.
