### ISSUE TITLE
Can't change rating of track (and it's difficult to figure it out how to do that)

### ISSUE THREAD

**Issue by shalnoff** [clementine-player/Clementine#4694]
Hi, 
thank you for great player! 

The problem is.... when I'm trying to add rating to the track

1. that's really not obvious how to do this. It would be great to have like in RythmBox: Just 5 stars in column, and user can click on it to rate the track. In Clementine I found just the long way: left mouse button -> Edit Track information -> rating -> Click SAVE. 
2. Even by this way it doen't works. After user save it, nothing is changing. It's pretty annoying. 

Please fix this usefull issue.

**Comment by davidsansome** [comment]
You should be able to change the rating by adding the Rating column (right click on one of the other column headers and select Rating) and then clicking one of the 5 stars.  This only works for songs in your library.

**Comment by shalnoff** [comment]
There are no stars unfortunately. Just blank area. 
I have Linux Mint (based on Ubuntu Precise 12.4) Clementine 1.2

**Comment by diemenator** [comment]
Why is it closed? Reproduced this on win 10 x64, version 1.2.3, qt version 4.8.3
![image](https://cloud.githubusercontent.com/assets/7110483/13895282/78332faa-ed82-11e5-9263-d99a4d73db95.png)

No stars are visible on a playlist. Tried to disable all the appearance effects, moved columns around, etcetera, no luck.

**Comment by DoctorSubtilis** [comment]
I have the same issue: no stars, no possibility rating a file mp3.

**Comment by DoctorSubtilis** [comment]
Now solved: added files to library. So is possible assign rating!

**Comment by anderigs** [comment]
Hi,
I just had the same problem but maybe solved it - at least my problem . and wonder if you are also having the same problem:
1. as mentioned above if I add tracks via the library view this works
2. also in the file view it works IF this folder is in my "scanned folders" list
BUT and here was my problem: this doesn't work with symbolic links. You see I had something like this:

- scanned folders list: /home/Dropbox/music
- ln -s /home/Dropbox/music /home/ande/Music
- and I was USUALLY accessing the tracks via /home/ande/Music <- in this case I had no ratings available
- if I changed my access to the same tracks via /home/Dropbox/music THEN I had ratings available :-)

Hope this helps somebody else cos I was going slowly insane in trying to understand what was going on :-)
Still the best EVER music player!!! Thanks!

**Comment by uvwild** [comment]
That all being said there are to be ways to add files from the library to the player so that they dont make it into the library.

If you put new files INSIDE the library folder and add them to a playlist, the stars only show up AFTER the next rescan. (I have disabled automatic rescan due to the size of the library ;)

This does make sense but the UI doesn tell you this, so I banged my head a while why this happened ....

**Comment by uvwild** [comment]
Also I really think this should have nothing to do with library or not!

If someone could point out  why exactly no player seems to manage to just  update the tags (mp4/mp4/whatever)  in the media files correctly I would be very happy. 

This issue is bugging me for years with every player I tried.
They all seem to be able to maintain their own librabry more or less, but this tag update which would make it really useful when you move tracks between devices I have never seen resolved.

Any ideas?

is maybe the  "unified tag library" missing?

**Comment by bienenboris** [comment]
Nice. Thanks for all the useful and understandable comments.

You know, I made Clementine my test Music Player now. I miss one RATING FEATURE:
I wanna switch from 5 stars to FAVORITE OR NOT (heart/empty heart). 
Like in Elisa - a great lightweight QT player..

Is that possible with Clem?

thank
![2022-July-ELISA](https://user-images.githubusercontent.com/79990263/177204417-a61c676f-ea4b-459b-b8ff-bb24d2f72e99.png)
s
