### ISSUE TITLE
Collapsing the sidebar doesn't work

### ISSUE THREAD

**Issue by lahwran** [clementine-player/Clementine#4772]
So it used to be that I was able to collapse the clementine sidebar just by dragging the divider to the left far enough. It would stick at the sidebar's minimum size for a moment, and then disappear entirely. However, that doesn't seem to work anymore - it gets stuck at the minimum size of the sidebar, and then simply won't go any smaller or disappear. However, I tried varyingly old versions of clementine, and none of 1.2.2, 1.1.0, or several nightly builds inbetween, allowed me to collapse the sidebar. The odd thing is I *know* it worked at some point on 1.2.2. I'm not sure what changed. I'm on mac.

**Comment by sobkas** [comment]
So you want to have this functionality back/added?

**Comment by lahwran** [comment]
yeah. at this point I'm unsure whether it ever properly existed - something must have, I'm quite sure it worked at one point - so either back or added, whichever it is.

**Comment by ArnaudBienner** [comment]
This is intended: too many people accidentally collapse the sidebar and were confused when the sidebar wasn't visible anymore, so we changed this to prevent the sidebar to disappear entirely.

**Comment by lahwran** [comment]
please reopen this issue - what I want is a way to make it go away, not necessarily the same way. I noticed there's a right click menu now, could it be put in there?

**Comment by ArnaudBienner** [comment]
I think it would be too dangerous.
Maybe a right click option or something would be less dangerous than the previous behavior, but still, I'm sure some people will sometimes unintentionally hide this sidebar and struggle to get it back.
Is it really so important to you to be able to hide it? Currently it can be resized a lot.

**Comment by lahwran** [comment]
It wouldn't be the end of the world to not have it, but the thing is, it looks pretty cluttered to have the sidebar there :/ I use it so little that I'd rather just have it gone when I don't want it.

**Comment by ArnaudBienner** [comment]
Actually this seems to be a duplicate of #938

**Comment by lahwran** [comment]
ah, yep. close as dupe, and I'll comment over there to bring the thread alive

**Comment by ginsterbusch** [comment]
So, this is intended "usability"? Sounds like a load of bollocks.

That is the actual reason why I STOPPED using Clementine, thinking it's broken and waiting for a fixed release. 

You could just add a simple setting like "Show left sidebar [ ]" or a view option into the file menu, just like any other proper application gets it done, and all would be happy. And while being at it: Adding a (customizable) hotkey might not be such a bad idea, too ;)

cu, w0lf.

**Comment by ArnaudBienner** [comment]
@ginsterbusch If you want to use a player with billions of useless options like the one you propose, and with a behavior that can make it appear broken to most of the users, sure, Clementine isn't for you.

**Comment by ginsterbusch** [comment]
@ArnaudBienner I am not aware I've been "proposing" any kind of player. But yes, I prefer moc oder cmus over Clementine these days. Probably with plentyful of useless options and clutter, but then, what do I know ..? ^_^

cu, w0lf.

**Comment by Gibbz** [comment]
Any update on fixing this so that the side bar can be removed?

It really sucks having this huge wasted space to the side now that it cant be hidden or removed :(

**Comment by tabney00** [comment]
If it bothers you a lot and you like minimal interfaces, Audacious lets you remove many of the GUI elements.

**Comment by kiuuik** [comment]
I also would like to have back the option to completly hide the sidebar (though I can understand why you removed this feature)

My motivation: I have installed Clementine on several Macs for older people who had imported their CDs into the Computer and who were completly lost in iTunes. Instead of using the libary I put all CDs into one big playlist. When they want to play a music they can easily type in "White Album" and then they see what they expect. So they don't have to change any views or open any sidebar. It's just starting the program and typing what you want to hear. I also use this for myself because it's just faster. 

I think the filter bar in Clementine makes it pretty unique. I have tried many other media players. Audacious might offer to hide the side bar but the filter feature is weak. I also don't like the implementation of playlist filtering in foobar2000(on windows) or deadbeef because for filtering they open an additional window. I know that vlc offers similar playlist filtering but sometimes it opens in a different view or when people watch a video the playlist accidently disappears. Having multiple playlists in Clementine is also much easier because most people are familiar with tabs on top.

I use Clementine 1.3.1 but don't see a side bar. At some point I had to restore my .config folder from an older backup when I was still using 1.2.3. After his 1.3.1 read my config file from 1.2.3 without any problems. 

In the file ~/.config/Clementine/Clementine.conf there is a line "splitter state" under the heading [Main Window]. I think you can modify it to hide the side bar in 1.3.1. The side bar settings are somewhere in the middle of this line. Even if this breaks in future updates it shouldn't be a big problem because distros like UbuntuLTS or Debian don't update Clementine frequently. So you're good for another year or two?

Anyway - thanks for this fantastic software.

**Comment by peterjosvai** [comment]
I would be happy to be able to make it disappear, too... it is actually annoying that I untick "show sidebar" and it keeps coming back...
I think it is a mistaken strategy to assume that some people wouldn't be able to find the show sidebar option..

I love Clementine and I'm grateful, but/and I find it weird to be forced to see dropbox, google, opendrive etc... in a list all the time... I would like to play music... using playlists... and for that the sidebar is totally superfluous.. 

thank you anyway!
