### ISSUE TITLE
Opus files will not play

### ISSUE THREAD

**Issue by Jinglesassy** [clementine-player/Clementine#4791]
Under the Windows version of clementine .opus files will not play and give this error.

![clementine_error_2015-04-05_01-33-36](https://cloud.githubusercontent.com/assets/5727164/6995894/20e7fcdc-db34-11e4-92b1-9fee6591f268.png)

Tested with the latest development release and the last stable release, Both have the same issue. The same file plays fine in foobar2000 and VLC. I tried installing Gstreamer to see if that would help to no avail.

**Comment by Rewarp** [comment]
I can confirm it is not working for Version 1.2.2 on OpenSUSE 13.2 as well. Amarok plays the same files without issue.

**Comment by Chocobozzz** [comment]
Try to install gstreamer bad plugins.

**Comment by Rewarp** [comment]
Thanks for responding.

gstreamer-plugins-bad version 1.4.5-83.1 has already been installed prior to making comment.

**Comment by Chocobozzz** [comment]
I you use the latest release version (1.2.*) you need gstreamer 0.10.

gstreamer 1.4.* is for the git version of Clementine.

**Comment by Rewarp** [comment]
Thanks. Switched to the git version of Clementine and now it all works.

**Comment by therealromster** [comment]
Not sure why I am getting a email for this, crux has contrib/clementine and depends on gst-plugins-bad-compat. -compat versions of gstreamer are the old 0.10.x versions.

**Comment by RafaelLinux** [comment]
It's february 16 and still not able to play Opues files with Clementine. I just installed OpenSUSE 42.1 and can play Opus files inside the browser, with Amarok and even with SMplayer, but Clementine don't let me play Ogg/Opus files. What's up here? Any solution, please?

**Comment by Rewarp** [comment]
I just tested with my new Tumbleweed setup, where Clementine did not play Opus out of the box. Basically getting it to run requires the installation of gstreamer-0_10-plugins-bad, which was already mentioned in the thread.

Getting the proper version means subscribing to the Packman repositories https://en.opensuse.org/Additional_package_repositories

**Comment by RafaelLinux** [comment]
Thank you Rewarp

I just had installed  that codec, but I discovered the problem is not codec related. I think the problem is related to the way Clementine process that file. The file (that I will attach) is played without problems In in Chromiun,  SMPlayer and Audacios,  but Firefox showed me "file is damaged" and Clementine don't let me add that file to the playlist. 

With any other Opus file, Audacious shows me bitrate o each audio, but Clementine shows a empty bitrate.

So I think Clementine and Firefox are not working fine with Opus format.

Any suggestion?
[Rome - Sex you up (160kbit).ogg.zip](https://github.com/clementine-player/Clementine/files/140494/Rome.-.Sex.you.up.160kbit.ogg.zip)

**Comment by Rewarp** [comment]
It's an opus file but the extension is ogg. As soon as I renamed it, I could play it it Clementine.

**Comment by Ferroin** [comment]
A more correct statement would be that it's an Opus stream in an Ogg container file.  Ogg is not itself an audio codec, it's just a bitstream serialization format used to contain data from other multimedia codecs.  All Opus files (as far as I know) use the ogg bitstream format, but not all ogg files are opus streams (it can also contain theora video streams, vorbis or FLAC audio streams, and there's even a PCM based audio format derived from it).  Prior to 2007, the Xiph.org recommendation was to use .ogg for all stream types contained in the the Ogg bitstream format.  In 2007, they changed this recommendation to state that you should use a content specific file extension (because of poorly written software that can't understand the concept of format detection based on content not metadata), and thus Clementine and Firefox are technically correct in their behavior, although they should arguably be fixed to look at the file content instead of the extension to determine what codec to use.

**Comment by RafaelLinux** [comment]
Really deep and full of knowledge explanation. So I agree with you, Clementine and Firefox should fix this "problem". Thank you Ferroin.
