### ISSUE TITLE
New domain http://groovesharks.org

### ISSUE THREAD

**Issue by gleriston** [clementine-player/Clementine#5071]
groovesharks the domain changed http://www.grooveshark.com/ to http://groovesharks.org

**Comment by damianb** [comment]
Color me amazed.  The reason grooveshark went down was because of the RIAA hounding them for doing very...questionable practices in terms of streaming.  Really, there was no way for it to be legal.

I don't see this new incarnation lasting long.  It'll be a game of whack-a-mole.

TBH, grooveshark support should not be switched between domains; it should be removed entire.

**Comment by ArnaudBienner** [comment]
AFAICT Grooveshark *is* down and those websites are just clone reusing the same name.
