### ISSUE TITLE
Lyrics website for bollywood songs and albums

### ISSUE THREAD

**Issue by Shriyanshagro** [clementine-player/Clementine#5109]
Try adding some lyrics website for bollywood songs and albums . Or give permission to user to add website dynamically.

**Comment by narunlifescience** [comment]
Could you suggest some bollywood lyrics website (one or two best ones)? I will try to create a pull request ..

**Comment by Shriyanshagro** [comment]
1. http://www.bollywoodlyrics.com/
2. www.lyricsmaza.com/
3. http://www.hindilyrics.net/

These are some good bollyeood lyrics website ,, you can checkout for more if they doesn't satisfy the requirement.

**Comment by narunlifescience** [comment]
Added bollywoodlyrics.com & hindilyrics.net. www.musixmatch.com also provide limited bollywood lyrics support which is already present in clementine.

**Comment by Shriyanshagro** [comment]
Can you please tell me how to add this changes on my local machine??

**Comment by narunlifescience** [comment]
you should wait until a new developer build is created with the new changes. you can download the latest developer builds here : http://builds.clementine-player.org/ 
 However, the latest developer build available for download was built on 03-Nov-2015. so you should wait for a little while. 
If you are on a linux system you can clone the repo and build on your own (instructions available @ https://github.com/clementine-player/Clementine/wiki/Compiling-from-Source). Otherwise it would be pretty hard in case of windows or mac.

**Comment by hatstand** [comment]
buildbot is fixed and has caught up so new builds are available on http://builds.clementine-player.org/

**Comment by Shriyanshagro** [comment]
Thanks for all the efforts and accepting the request.
