### ISSUE TITLE
Shortcut conflict in Spanish localization

### ISSUE THREAD

**Issue by Pastafarianist** [clementine-player/Clementine#5164]
![image](https://cloud.githubusercontent.com/assets/1315874/11918796/c1a1b65c-a750-11e5-9d82-090ff49eab20.png)

`Ctrl+T` is assigned both to the autotagger and the converter.
Latest Clementine compiled from the repository, Gentoo Linux.

**Comment by santigl** [comment]
In file `src/main_window.ui` they have different bindings: `Ctrl+T` for the auto-complete and `Ctrl+Shift+T` to add to the converter. 

They effectively conflict in the Spanish translation (it's not just the label), but in English they don't.

**Comment by santigl** [comment]
Ok, the problem seems to be the fact that the key names are translated in the .po files. (For example `Shift` -> `Mayús`.) And this happens with other translations besides Spanish.

By leaving the shortcuts as they originally appear in English, everything works as expected. 

From the QT docs: 
> Warning: Do not translate the "Alt", "Ctrl" or "Shift" parts of the accelerators. Qt relies on these strings being there. For supported languages, Qt automatically translates these strings.

I would prepare a fix, but I don't know if it is ok to edit translations files directly into the repo.

**Comment by Chocobozzz** [comment]
Thanks for reporting it :)

Closed by https://github.com/clementine-player/Clementine/pull/5169
