### ISSUE TITLE
Double clicking an album to play it is not actually fixed in 1.3.1 (old issue #5226)

### ISSUE THREAD

**Issue by mmccoy37** [clementine-player/Clementine#5361]
Can this issue be reopened? I left a comment with a gif demonstrating this behavior in the latest 1.3.1 build, even though the issue was supposedly fixed in 1.3.0.

#5226 
https://github.com/clementine-player/Clementine/issues/5226#issuecomment-214591697

**Comment by narunlifescience** [comment]
this is in fact fixed but not included in 1.3 release.. try latest developer builds from https://builds.clementine-player.org/ make sure to download latest 1.2.3 build not 1.3.xx

**Comment by mmccoy37** [comment]
My bad, I assumed 1.3.1 was the latest, even after the clone build defaulted to 1.2.3...
I will rebuild this tonight. Thank you

**Comment by GitHorst** [comment]
( @narunlifescience ?)
I am on LinuxMint 17.2 and I have "me-davidsansome/clementine" added to my PPAs. As far as I understand this is the source for the latest stable build -- is it?

Seeing how this issue has been reported [months ago](https://github.com/clementine-player/Clementine/issues/5226) already I wonder: when will the fix make it to the stable release(/the PPA)?

Thanks for your efforts with this awesome program! :)

**Comment by narunlifescience** [comment]
yes, you are right... but as i mentioned in previous comment the fix is not included in 1.3.xx yet (only fixed in git master branch). if you would like to use this feature you may have to clone the repo and build clementine from source or download test build from https://builds.clementine-player.org/. make sure to download latest 1.2.3 build not 1.3.xx (this is because the master branch is still built with 1.2.3 designation).

**Comment by narunlifescience** [comment]
after a quick look on status of the commit, I find the fix is on the way (included in 1.3.2rc). this should be fixed in the latest developer build. there is a test build available
64 bit - https://builds.clementine-player.org/debian-jessie/clementine_1.3.2~rc1~jessie_amd64.deb
32 bit - https://builds.clementine-player.org/debian-jessie/clementine_1.3.2~rc1~jessie_i386.deb

**Comment by GitHorst** [comment]
@narunlifescience great, thanks for the info! keep up the good work :)

**Comment by DanielPower** [comment]
More than a year later, this fix still is not released in a stable build. Extremely disappointing.
