### ISSUE TITLE
Can't "Save playlist" with colon in name

### ISSUE THREAD

**Issue by szarka** [clementine-player/Clementine#5460]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.
- [ x] I checked the issue tracker for similar issues
- [x ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)
### System information

Please provide information about your system and the version of Clementine used.
- Operating System: Windows 10 Home, Version 1511, Build 10586.494
- Clementine version: 1.3.1
### Expected behaviour / actual behaviour

When attempting to export ("save") playlist (to m3u or any other format), playlists with a colon (:) in the name, nothing happens (not even an error). Renaming the playlist to remove the colon enables expected behavior ("save playlist" dialog pops up).
### Steps to reproduce the problem (only for bugs)
1. Create a playlist whose name includes a colon (anywhere in the filename).
2. Right-click on playlist in Playlists window.
3. Choose Save.

Result should be no save playlist dialog.
1. Rename playlist to remove the colon.
2. Right-click on playlist in Playlists window.
3. Choose Save.

Result should be expected save playlist dialog.

**Comment by mananaBanana** [comment]
Perhaps this is because [Windows] (https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx) doesn't support colons in the filename. Can you try this with any of the other invalid symbols mentioned in the link? This could be an OS issue instead of a bug with clementine.

Could we have a Windows-only patch that converts illegal symbols into legal ones (like dashes or dots) before saving?
