### ISSUE TITLE
[qt5] Fails to build on Arch

### ISSUE THREAD

**Issue by beojan** [clementine-player/Clementine#5608]
Clementine-qt5 fails to build on Arch (from AUR) with error:
```
[100%] Linking CXX executable ../clementine
/usr/bin/ld: libclementine_lib.a(database.cpp.o): undefined reference to symbol 'sqlite3_backup_pagecount'
/usr/lib/libsqlite3.so.0: error adding symbols: DSO missing from command line
```

**Comment by Chocobozzz** [comment]
Go directly to https://aur.archlinux.org/packages/clementine-qt5-git/ for AUR bugs.

**Comment by jcelerier** [comment]
Just doing the following steps (which are basically what the aur package is doing anyways)

    git clone https://github.com/clementine-player/Clementine.git -b qt5
    mkdir build ; cd build 
    cmake ../Clementine
    cmake --build . 

fails similarly

**Comment by jcelerier** [comment]
It works if in the link line I replace /usr/lib/libsqlite3.so by -lsqlite3

**Comment by rigred** [comment]
Do any of you have the `aur/leap-motion-driver` package installed? 
I'm asking because the maintainer of that package package sqlite3 into leap-motion-driver with  
`/usr/bin/libsqlite3.so` 

As well as various other packages that should NEVER be included like that.

```
leap-motion-driver /usr/bin/libfreebl3.so
leap-motion-driver /usr/bin/libnspr4.so
leap-motion-driver /usr/bin/libnssdbm3.so
leap-motion-driver /usr/bin/libnssutil3.so
leap-motion-driver /usr/bin/libplc4.so
leap-motion-driver /usr/bin/libplds4.so
leap-motion-driver /usr/bin/libsoftokn3.so
leap-motion-driver /usr/bin/libsqlite3.so
```

This breaks plenty of others things but particularly cmake, cmake instead of finding the `/usr/lib/libsqlite3.so` package uses `/usr/bin/libsqlite3.so` - some entirely different build of sqlite that does - that I'm not entirely sure I trust.

https://aur.archlinux.org/packages/leap-motion-driver/

If you don't have the leap-motion-driver - check that there isn't some other library in the /usr/bin directory that's being loaded instead with the cmake compile. 

`-lsqlite` btw behaves correctly and links the `/usr/lib/libsqlite3.so` file.

**Comment by jcelerier** [comment]
ah, for me that may have been the case indeed (I'm not 100% sure since I prune my packages regularly but I've used the leap so I may have installed it at some point).

**Comment by rigred** [comment]
Btw: I updated the leap-motion-driver package to move the libs into a Leap specific sub directory.
Unfortunately that came at the cost of angering the original maintainer who abandoned the project onto me. :( 

So I'm now maintaining it
