### ISSUE TITLE
liblastfm support in qt5 branch

### ISSUE THREAD

**Issue by aelzenaar** [clementine-player/Clementine#5949]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch Linux (fully updated today)
- Clementine version:  Git qt5 (902c22ef, up to date with origin/qt5 as of [today)](url)

### Expected behaviour / actual behaviour
When compiling on master (with qt4), liblastfm is detected and scrobbling works. When compiling on the qt5 branch, liblastfm is not detected.

### Steps to reproduce the problem (only for bugs)
Ensure that liblastfm is installed.
```bash
    git checkout qt5
    cmake
```
And note that
```
    Last.fm support (missing liblastfm)
```
is output by cmake.

**Comment by trougnouf** [comment]
You need https://aur.archlinux.org/packages/liblastfm-qt5/

**Comment by aelzenaar** [comment]
I swear I checked the AUR and didn't see that package... closed. Thanks!

**Comment by quezak** [comment]
Dropping a comment since I had the same problem on Gentoo Linux and found this issue. 

Workaround: install the git version `liblastfm-9999` from the KDE overlay.

Explanation: cmake, when looking for `liblastfm` with `qt5` enabled, looks for `lastfm5/ws.h` and `lastfm5/Track.h`. Seems like the current `liblastfm-1.0.9-r1` ebuild, with `qt5` USE flag enabled, only builds the shared library `liblastfm5.so` -- doesn't create the separate `/usr/include/lastfm5` directory, just the old `/usr/include/lastfm`. The git version installs both.
