### ISSUE TITLE
Not Moving To Next Song In Playlist

### ISSUE THREAD

**Issue by darkphoenixff4** [clementine-player/Clementine#6062]
I'm using Clementine 1.3.1 on Manjaro Linux, and have also seen this if I build the clementine-qt5-git package from the repository.  For whatever reason, randomly when Clementine gets to the end of a song, it will stop at the end and just sit there until I click on the playbar.  I noticed there are old bug reports about it not playing new songs, but in those reports it's at least moving to the next song in the playlist; here, it isn't even doing that.  It's just freezing at the end of the song.  And no, it's not stopping playback, it's just freezing at the end of the song.  As I said, if I click anywhere on the seek bar, it'll start playing the next song at the point I clicked at, so it's clearly moving to the next song; it just doesn't seem to be actually starting playback.  Not sure what exactly is going on here.

**Comment by raphj** [comment]
I have the exact same issue.
I observe the bug in the latest git build of Clementine and Clementine-qt5, as well as in the Debian testing and Ubuntu Bionic provided versions of Clementine on i386, x86_64 and arm64.

I could observe that the bug is not present in version 1.2.3 of Clementine (Ubuntu Xenial).
So something broke between Clementine 1.2.3 and Clementine 1.3.1 or something changed in some related package.

**Comment by antika0n** [comment]
This has started happening to me to after upgrading to Ubuntu 18.04 last week.

**Comment by EBaisleyJr** [comment]
Running 64-bit Kubuntu 18.04, I'm experiencing the same issue.  I can hit next and playback will resume, but will often just stop again at the end of the next song, or the one after that.

**Comment by bhrgunatha** [comment]
[Arch linux 64 bit, Clementine 1.3.1](https://www.archlinux.org/packages/community/x86_64/clementine/) here with the same problem. 

Clementine was updated on 2nd of May but I've only _noticed_ it in the last week or so. 

I haven't changed my Clementine settings. 
Not sure if it's useful but upgrades of the (direct) dependencies of the Arch package since Clementine upgraded shows:

```
...
[2018-05-02 19:55] [ALPM] upgraded clementine (1.3.1-16 -> 1.3.1-17)
[2018-05-09 14:27] [ALPM] upgraded glibc (2.27-2 -> 2.27-3)
[2018-05-15 13:23] [ALPM] upgraded chromaprint (1.4.3-1 -> 1.4.3-2)
[2018-05-20 15:32] [ALPM] upgraded gst-libav (1.14.0-2 -> 1.14.1-1)
[2018-05-20 15:32] [ALPM] upgraded gst-plugins-base (1.14.0-1 -> 1.14.1-1)
[2018-05-20 15:32] [ALPM] upgraded gst-plugins-base-libs (1.14.0-1 -> 1.14.1-1)
[2018-05-20 15:32] [ALPM] upgraded gst-plugins-good (1.14.0-1 -> 1.14.1-1)
[2018-05-20 15:32] [ALPM] upgraded gst-plugins-ugly (1.14.0-1 -> 1.14.1-1)
[2018-05-20 15:32] [ALPM] upgraded gstreamer (1.14.0-1 -> 1.14.1-1)
[2018-05-23 13:49] [ALPM] upgraded mesa (18.0.3-4 -> 18.0.4-1)
[2018-05-29 11:03] [ALPM] upgraded fftw (3.3.7-1 -> 3.3.8-1)
[2018-05-31 17:30] [ALPM] upgraded boost-libs (1.66.0-2 -> 1.66.0-3)
[2018-05-31 17:30] [ALPM] upgraded gst-plugins-bad (1.14.1-1 -> 1.14.1-2)
[2018-06-05 11:18] [ALPM] upgraded cmake (3.11.2-1 -> 3.11.3-1)
[2018-06-05 11:18] [ALPM] upgraded libglade (2.6.4-5 -> 2.6.4-6)
[2018-06-05 11:18] [ALPM] upgraded liblastfm-qt4 (1.0.9-2 -> 1.0.9-3)
[2018-06-08 10:46] [ALPM] upgraded gcc-libs (8.1.0-1 -> 8.1.1+20180531-1)
[2018-06-08 10:46] [ALPM] upgraded gvfs-smb (1.36.2-1 -> 1.36.2-2)
```

I can't see a common cause, but I found one track that seems to cause a consistent pause when it's the **2nd track** in a playlist but not the _1st or 3rd_.

**Comment by bhrgunatha** [comment]
I've noticed a pattern and I think it's only 24bit flac files that are causing the freeze.  
It's not **all**  24 bit flac files but so far I think all the files that have frozen have been.    
Anyone else notice any pattern?

**Comment by raphj** [comment]
I currently have no flac files in my playlist.

**Comment by raphj** [comment]
It seems to have fixed the problem for me. Thanks!

**Comment by tholin** [comment]
Should the patch work on the qt5 branch?

Like most people I've been having this problem for a while. My distribution has discontinued qt4 so I use the qt5 branch and applied the "Attempt to fix track change hang" patch on it. It seemed to work fine at first. I don't get any hangs during track change anymore.

Now if I pause playback, keep it paused for over a minute and then unpause I only get silence. I've confirmed that the change was caused by that patch. If I pause less than 1 min the unpause works fine. If I pause for exactly 1 min the playback will sound garbled after unpausing.

**Comment by raphj** [comment]
I am using a modified version of the qt5 branch (master, merge https://github.com/clementine-player/Clementine/pull/5511 (Reduce some CPU load by disabling/fixing some UI stuff #5511), merge qt5)  and cannot reproduce the silence after pause.

By any chance is your Pulseaudio stream being redirected to another output PulseAudio sink? I've had problems with Clementine randomly switching Pulseaudio outputs when using Bluetooth headphones between tracks. Can't say if this is still the case, especially  with this patch. I use wired headphones most of the time now for unrelated reasons.

**Comment by tholin** [comment]
I don't use Pulseaudio at all. I'm one of those weird people who use ALSA directly.

Here are my playback settings from Clementine.conf

    [GstEngine]
    bufferduration=4000
    bufferminfill=33
    device=@Invalid()
    monoplayback=false
    rgcompression=true
    rgenabled=true
    rgmode=0
    rgpreamp=@Variant(\0\0\0\x87\0\0\0\0)
    samplerate=-1
    sink=autoaudiosink
    
    [Player]
    AutoCrossfadeEnabled=false
    CrossfadeEnabled=true
    FadeoutDuration=2000
    FadeoutEnabled=true
    FadeoutPauseDuration=250
    FadeoutPauseEnabled=false
    NoCrossfadeSameAlbum=true
    menu_previousmode=1
    seek_step_sec=10
    volume=100

**Comment by fernandoluizao** [comment]
Same problem. It would be possible to release the current master as 1.3.2?

**Comment by ledroide** [comment]
Maybe the same problem as #4748

**Comment by Wurzelmann** [comment]
Same problem here, but for me it always hangs, when a the next song in the playlist is from a different album than the last song's (all FLAC). Maybe coincidence and it is FLAC-related after all?
