### ISSUE TITLE
Clementine doesn't work on macOS Mojave

### ISSUE THREAD

**Issue by slallum** [clementine-player/Clementine#6148]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: macOS Mojave, MacBook Pro (15-inch, 2017).
- Clementine version: 1.3.1, also tried 1.3.2rc1.

### Expected behaviour / actual behaviour
Clementine is opening, showing the main window for a split second and then quits.

### Steps to reproduce the problem (only for bugs)
Upgrade to Mojave and open Clementine.

**Comment by slallum** [comment]
Solved it.
Turns out I need to give accessibility control to Clementine under "Security and Privacy" preferences:

![image](https://user-images.githubusercontent.com/3120686/46147356-fdcb8f00-c26d-11e8-9970-d5e986c0ea7e.png)

**Comment by edwardgalligan** [comment]
@slallum I also experienced this, so thanks for posting the workaround. However, since it's a workaround and not a bugfix (the bug still exists), it might be worth leaving the issue open?

**Comment by ovichiro** [comment]
Why does Clementine need accessibility control?

**Comment by DarthVaderx99** [comment]
it is not just clementine all (third party?) apps need it now in mojave

**Comment by hatstand** [comment]
IIRC, it's because Apple doesn't let you use the media keys any other way.

**Comment by ovichiro** [comment]
> it is not just clementine all (third party?) apps need it now in mojave. and new now apple requires you to say yes to letting app have privilages the first time it is opened in mojave, apples new way of checking malware?!?!

That dialog is indeed intended to prevent apps adding themselves automatically to accessibility control, but no, not all third party apps require accessibility. Cantata works fine without it and since Clementine also defines it's own keyboard shortcuts it shouldn't crash if I don't grant it permission for such control.
@hatstand  is probably right. Thanks.

**Comment by edwardgalligan** [comment]
> it is not just clementine all (third party?) apps need it now in mojave

This definitely isn't true or there'd be a similar issue to this on every macOS app bugtracker out there.

As @hatstand pointed out, Clementine (and I guess most music players) do use explicit accessibility features. However, it probably shouldn't crash the entire app when that one feature isn't available.

**Comment by hatstand** [comment]
Yeah, clementine is supposed to check if it's enabled and if not, open the accessibility dialog for you. But I'm guessing Apple's API changed in Mojave. I don't really have time to look into it but the code if you're interested is here:

https://github.com/clementine-player/Clementine/blob/master/src/core/mac_startup.mm
https://github.com/clementine-player/Clementine/blob/master/src/core/macglobalshortcutbackend.mm#L130

and we use https://github.com/nevyn/SPMediaKeyTap which hasn't been updated since 2015...

**Comment by jrkong** [comment]
I'll do a bit of digging to see if I can get this to run.

**Comment by jrkong** [comment]
@hatstand seems like the crash occurs because `AXAPIEnabled()` has been depreciated since Mavericks (macOS 10.9). I updated the code to fallback to the call used by Mavericks and later if the `AXAPIEnabled()` call fails in my PR so the crash doesn't occur anymore.

**Comment by benlk** [comment]
For newer versions of OSX, https://developer.apple.com/documentation/mediaplayer/mpremotecommandcenter provides access to the media player actions.

**Comment by hatstand** [comment]
Shouldn't be too hard to update Clementine to use that here instead then: https://github.com/clementine-player/Clementine/blob/master/src/core/macglobalshortcutbackend.mm

I'd do it but I don't have a mac anymore.

**Comment by KAMIKAZEUA** [comment]
Same here. Mojave 10.14.3.

I just downloaded official version 1.3.1 and got that crash. 
However when I downloaded version from latest builds, it was Jan 28 and it's runs ok, but problem was - I can't import any files, nothing happens.

**Comment by ssbarnea** [comment]
I am wondering why this bug is closed as clearly this is a deal breaker. That is the first MacOS that is effectively instanly crashign when Accesibility access is not enabled, clearly a very bad first time user experience.

**Comment by benlk** [comment]
As an outsider, this bug appears to be closed because:
- a fix was merged to master in https://github.com/clementine-player/Clementine/pull/6210
- the primary dev no longer has a Mac

People are wondering why this issue is closed when the bug still occurs because:
- the last release of Clementine was in 2016, before #6210 was merged
- there has been no published release since 2016: https://github.com/clementine-player/Clementine/releases

**Comment by grnadav** [comment]
> As an outsider, this bug appears to be closed because:
> 
> * a fix was merged to master in #6210
> * the primary dev no longer has a Mac
> 
> People are wondering why this issue is closed when the bug still occurs because:
> 
> * the last release of Clementine was in 2016, before #6210 was merged
> * there has been no published release since 2016: https://github.com/clementine-player/Clementine/releases
> * the nightly OSX build server advertised at https://www.clementine-player.org/participate is not responding: https://builds.clementine-player.org/mac/

https://builds.clementine-player.org/mac/ - work for me now. used latest 1.3.1 build and the issue is indeed resolved

**Comment by hipunk** [comment]
Sorry for going semi-off-topic, but it's kind of true what @DarthVaderx99 says, considering you're using some services based on AppleScript from the services menu. You need to add _every single application_ to the accesibility list then.

**Comment by MrSmiths** [comment]
after upgrade High Sierra to Mojave clementine crashes.. removed.. downloaded 1.3.1.. install.. crash..
permiting accessibility control solved the issue.. Thanks @slallum
