### ISSUE TITLE
[Question] Is it possible write plugins/extensions/scripts for clementine?

### ISSUE THREAD

**Issue by LoveIsGrief** [clementine-player/Clementine#6185]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

- Operating System: Kubuntu 16.04
- Clementine version: 1.2.3

### Question

> Is it possible write plugins/extensions/scripts for clementine?

I haven't found documentation to do so nor any issues answering this question. IIRC Clementine was forked from Amarok, which does have a plugin system.

It would be really great to be able to so, since C++ is not my language of choice.

**Comment by hatstand** [comment]
No.

**Comment by LoveIsGrief** [comment]
Is it planned at all?

**Comment by ccoenen** [comment]
I was wondering the same thing. I'm in the process of switching over from Media Monkey. There, I use a tiny script that is called every time a new track starts. This is very versatile and I depend a little bit on this.

**Comment by Venryx** [comment]
Same for me, would be quite nice.

My use case is the following:
[]()==========
So let's say you're like me and you have a large collection of music. However, you also recently added a new batch of music that you really like. You want to hear that new batch of music a lot, but you also don't want to hear that new music *exclusively*, otherwise it will cause the enjoyment factor to decay too fast.

So you want your full collection in the playlist, but have the playlist "biased" to where it over-represents the new music by a certain amount in the mix. In other words, a way to "weight" new music with an arbitrary "frequency multiplier".
[]()==========

I like Clementine Player a lot, but lacking a script/extension system is a serious lack in my opinion. That said, I understand it's a pretty large feature to add, so it seems unlikely that it will be added anytime soon. (I'd look into it myself if it were in a language I had experience with, but I've only touched C++ code a few times in my life ^_^)

In the mean-time, I'm looking into some other open-source players with scripting languages, like Amarok.

If the other players don't pan out (for example, if they lack Clementine's auto-playlists and/or replay-gain auto-equalization), I'll look into creating a script that interacts with the network api as provided here:
https://github.com/jjmontesl/python-clementine-remote
https://github.com/clementine-player/Android-Remote/blob/master/app/src/main/java/de/qspool/clementineremote/backend/pb/remotecontrolmessages.proto

**Comment by LoveIsGrief** [comment]
I can recommend [Quod Libet](https://quodlibet.readthedocs.io/en/latest/development/plugins.html). They have pretty good plugin support and nice list thereof.
