### ISSUE TITLE
Clementine crashes on Mac OS X 10.14.1 (18B75)

### ISSUE THREAD

**Issue by neevn** [clementine-player/Clementine#6200]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ ] I checked the issue tracker for similar issues: ok
- [ ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved: ok
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/): ok

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Mac OS X 10.14.1 (18B75)
- Clementine version: 1.3.1 (4096.1.3.1.1)

### Steps to reproduce the problem (only for bugs)

1. Install the app
2. Open the app
===>Error occurs
<img width="995" alt="screen shot 2018-11-12 at 15 20 02" src="https://user-images.githubusercontent.com/5276333/48334805-79529580-e68e-11e8-842d-1cfac171cfc9.png">

**Comment by dynched** [comment]
I had the same issue after upgrading to 10.14.  As a workaround, I enabled clementine.app in 'Allow the apps below to control your computer' in the accessibility section of security and privacy, which allowed clementine to launch normally.

see attached

![clementine_10 14](https://user-images.githubusercontent.com/25484508/48368136-e0694d80-e680-11e8-9811-afe72cbd5ede.png)

**Comment by neevn** [comment]
It works. Thank you

**Comment by gomera** [comment]
These things will keep happening if we don't get a new version of the app in years ....

**Comment by gomera** [comment]
@jrkong I think I wasn't clear enough. I am not talking about this precise Mojave thing. I am talking that since we don't have a release in two years, the latest stable binary will be more likely to be less compatible with newer versions of any OS day by day ... 

Clementine 1.3.1 was release on Apr 2016, if we are talking just about Apple, then we have Sierra September 2016, High Sierra September 2017 and now Mojave September 2018. I was just pure luck that we didn't get any breaking change for 2 years and a half ...

can you see the problem ?

**Comment by jeanrajotte** [comment]
BTW,  @dynched "fix"
> I had the same issue after upgrading to 10.14. As a workaround, I enabled clementine.app in 'Allow the apps below to control your computer' in the accessibility section of security and privacy, which allowed clementine to launch normally.

works, but you might have to insist.  Clementine 1st opened the Preference window, the checkmark was checked, and yet it crashed.  I had to do these steps for it to settle, after many crashes:

1. close Clementine and Preferences
1. open preferences manually
1. uncheck the Privacy / Accessibility / Clementine.app
1. check the Privacy / Accessibility / Clementine.app
1. open Clementine

and then it took.

**Comment by jeanrajotte** [comment]
p.s. I also 1st downloaded the latest, which may or may not have been what was installed. So it's possible Clementine was still crashing because of this Accessibility checkmark because it was not actually the same app (I'm spitballing here).  Once the new app was installed, I unchecked, then rechecked the checkmark, which possibly registered the right app (latest download).  Dunno...

**Comment by jrkong** [comment]
Fixed by #6210. It's not in a release but it's fixed and merged.

**Comment by liofeu** [comment]
Thanks, it worked for me
