### ISSUE TITLE
Clementine Crashing on Launch

### ISSUE THREAD

**Issue by baconomist** [clementine-player/Clementine#6290]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ x ] I checked the issue tracker for similar issues
- [ x ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ x ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Windows 7 Ultimate N x64
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
Clementine crashes on launch and is "not responding".
Problem signature from windows error window:
  ``` 
  Problem Event Name:	BEX
  Application Name:	clementine.exe
  Application Version:	1.3.0.0
  Application Timestamp:	571656ec
  Fault Module Name:	BfLLR.dll
  Fault Module Version:	8.0.3.11
  Fault Module Timestamp:	4ffc51b5
  Exception Offset:	0000e191
  Exception Code:	c0000409
  Exception Data:	00000000
  OS Version:	6.1.7601.2.1.0.256.28
  Locale ID:	1033
  Additional Information 1:	b798
  Additional Information 2:	b798accfa6af53c3cd382395cc58928e
  Additional Information 3:	2b19
  Additional Information 4:	2b1959b272841a5bebc797e3e343be6a
```

### Steps to reproduce the problem (only for bugs)
1. Launch clementine

Important:
I've recently reinstalled windows and copied my user data over.

Things I've tried:
- Using a different user
- Running as admin
- Reinstalling clementine
- Downloading a different version of clementine
- Deleting the directory %USERPROFILE%/.config/
- Deleting registry keys under HKEY_CURRENT_USER/Software/Clementine

**Comment by baconomist** [comment]
The issue seems to have resolved itself. Although, if any insight could be provided as to the cause of this issue that would be great.

**Comment by baconomist** [comment]
Reopening the issue since the problem is occurring again.

**Comment by oxoocoffee** [comment]
I just downloaded (1.3.1) and installed on Mac OS X 10.14.3 (18D109). Just so you know I am running in Dark Mode and I never did run Clamentine on my machine until today. This crash happens every time on start. 

`Process:               clementine [1229]`
`Path:                  /Applications/clementine.app/Contents/MacOS/clementine`
`Identifier:            org.clementine-player.clementine`
`Version:               1.3.1 (4096.1.3.1.1)`
`Code Type:             X86-64 (Native)`
`Parent Process:        ??? [1]`
`Responsible:           clementine [1229]`
`User ID:               501`
``
`Date/Time:             2019-03-11 12:00:15.396 -0500`
`OS Version:            Mac OS X 10.14.3 (18D109)`
`Report Version:        12`
`Anonymous UUID:        7E39FAC3-3EDC-61FE-F97A-BAD1B81674E8`
``
`Sleep/Wake UUID:       FE61D412-1B9B-4DF5-8D24-141CC1AB0E66`
``
`Time Awake Since Boot: 1600 seconds`
`Time Since Wake:       520 seconds`
``
`System Integrity Protection: enabled`
``
`Crashed Thread:        0  Dispatch queue: com.apple.main-thread`
``
`Exception Type:        EXC_BAD_ACCESS (SIGSEGV)`
`Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000`
`Exception Note:        EXC_CORPSE_NOTIFY`
``
`Termination Signal:    Segmentation fault: 11`
`Termination Reason:    Namespace SIGNAL, Code 0xb`
`Terminating Process:   exc handler [1229]`
``
`VM Regions Near 0:`
`--> `
`    __TEXT                 0000000105a10000-000000010686f000 [ 14.4M] r-x/rwx SM=COW  /Applications/clementine.app/Contents/MacOS/clementine`
` `
`Thread 0 Crashed:: Dispatch queue: com.apple.main-thread`
`0   com.apple.CoreFoundation      	0x00007fff508183ef CFMachPortIsValid + 14`
`1   com.apple.CoreFoundation      	0x00007fff508184b4 CFMachPortCreateRunLoopSource + 72`
`2   org.clementine-player.clementine	0x0000000105f4b59c -[SPMediaKeyTap startWatchingMediaKeys] + 92`
`3   com.apple.CoreFoundation      	0x00007fff50865632 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12`
`4   com.apple.CoreFoundation      	0x00007fff508655ac ___CFXRegistrationPost_block_invoke + 63`
`5   com.apple.CoreFoundation      	0x00007fff508654cd _CFXRegistrationPost + 398`
`6   com.apple.CoreFoundation      	0x00007fff5086d929 ___CFXNotificationPost_block_invoke + 87`
`7   com.apple.CoreFoundation      	0x00007fff507d50ca -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1633`
`8   com.apple.CoreFoundation      	0x00007fff507d448d _CFXNotificationPost + 742`
`9   com.apple.Foundation          	0x00007fff52b5ca7b -[NSNotificationCenter postNotificationName:object:userInfo:] + 66`
`10  com.apple.AppKit              	0x00007fff4dd5964a -[NSApplication _postDidFinishNotification] + 313`
`11  com.apple.AppKit              	0x00007fff4dd58f6e -[NSApplication _sendFinishLaunchingNotification] + 209`
`12  com.apple.AppKit              	0x00007fff4dd568c8 -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 552`
`13  com.apple.AppKit              	0x00007fff4dd56517 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 690`
`14  com.apple.Foundation          	0x00007fff52ba7144 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 287`
`15  com.apple.Foundation          	0x00007fff52ba6fc0 _NSAppleEventManagerGenericHandler + 102`
`16  com.apple.AE                  	0x00007fff51a8cb93 aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) + 1855`
`17  com.apple.AE                  	0x00007fff51a8c3fd dispatchEventAndSendReply(AEDesc const*, AEDesc*) + 41`
`18  com.apple.AE                  	0x00007fff51a8c2d5 aeProcessAppleEvent + 439`
`19  com.apple.HIToolbox           	0x00007fff4faa110e AEProcessAppleEvent + 55`
`20  com.apple.AppKit              	0x00007fff4dd52644 _DPSNextEvent + 1734`
`21  com.apple.AppKit              	0x00007fff4dd51102 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1362`
`22  com.apple.AppKit              	0x00007fff4dd4b165 -[NSApplication run] + 699`
`23  QtGui                         	0x0000000107f9b92a QEventDispatcherMac::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 554`
`24  QtCore                        	0x0000000108c3a7ea QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 394`
`25  QtCore                        	0x0000000108c3d067 QCoreApplication::exec() + 199`
`26  org.clementine-player.clementine	0x0000000105a1f3a4 main + 5620`
`27  libdyld.dylib                 	0x00007fff7da52ed9 start + 1`

**Comment by fivestones** [comment]
I'm on macos 10.14.4 with a new download of clementine 1.3.1, running it for the first time on this machine.

It crashes on launch for me every time. The first time it loaded enough to ask me if I wanted to do automatic updates, I clicked yes, and then it crashed. The second time (i think?) it loaded its window for a brief second and then crashed. Every other time it crashes before the window even loads.

I'm not using dark mode.

I can post the macos "problem details" stuff if you need them.

**Comment by roman-yerin** [comment]
Still crashing. Nobody cares, what a shame.

**Comment by hatstand** [comment]
At least _try_ to follow the instructions in the issue template: https://builds.clementine-player.org/mac/

**Comment by roman-yerin** [comment]
Yep, just close it without a fix :)
At least try to check links you give, there's no any template there. This is an open source project and nobody claims nothing, but you could be a little bit less smug, you know...

**Comment by hatstand** [comment]
The link has builds that work.

**Comment by roman-yerin** [comment]
No, it doesn't, I've just tried 1.3.1 and 1.3.2-rc2

**Comment by hatstand** [comment]
Try a newer one: https://www.googleapis.com/download/storage/v1/b/builds.clementine-player.org/o/mac%2Fclementine-1.3.1-945-g440ac6dda.dmg?generation=1575335244561385&alt=media

**Comment by roman-yerin** [comment]
This particular one opens successfully on my Mac. However, are you sure you want to close this issue, keeping in mind that 1.3.2-rc1 crashes?

**Comment by hatstand** [comment]
Yes, if it works on master.
