### ISSUE TITLE
Problems with ver. 1.3.1.44 from Snapd

### ISSUE THREAD

**Issue by beardedragon2** [clementine-player/Clementine#6422]
https://forum.manjaro.org/t/snap-packages-via-pamac/108515?u=beardedragon

**Comment by fitojb** [comment]
The proper repository to report issues with the snap package is this: https://github.com/kz6fittycent/clementine

With regard to bug reporting practices, I would suggest that instead of just dropping a link and calling it a day, you take the time to write the **one specific** issue you’re experiencing.
