### ISSUE TITLE
Spotify Blob Failed to Load

### ISSUE THREAD

**Issue by ghost** [clementine-player/Clementine#6569]
The Spotify plugin is failing to download. I already have the latest version 1.3.1, I've upgraded with the instructions [here](https://www.clementine-player.org/downloads) just to be sure. I have a Lubuntu 18.04

**Comment by jbroadus** [comment]
Looks like it redirects to a bucket instead of the file:

$ curl https://spotify.clementine-player.org/version16-64bit/blob
<!doctype html><body>
<div><a href="https://www.googleapis.com/download/storage/v1/b/builds.clementine-player.org/o/version16-64bit%2Fblob?generation=1580567215944396&alt=media"></a></div><div><a href="https://www.googleapis.com/download/storage/v1/b/builds.clementine-player.org/o/version16-64bit%2Fblob.sha512?generation=1580567216068289&alt=media">.sha512</a></div></body>

**Comment by jbroadus** [comment]
Fixed, as noted in issue #6562.

**Comment by fmlatghor** [comment]
> Looks like it redirects to a bucket instead of the file:
> 
> ```
> $ curl https://spotify.clementine-player.org/version16-64bit/blob
> <!doctype html><body>
> <div><a href="https://www.googleapis.com/download/storage/v1/b/builds.clementine-player.org/o/version16-64bit%2Fblob?generation=1580567215944396&alt=media"></a></div><div><a href="https://www.googleapis.com/download/storage/v1/b/builds.clementine-player.org/o/version16-64bit%2Fblob.sha512?generation=1580567216068289&alt=media">.sha512</a></div></body>
> ```

I don't understand. I don't even understand what you're doing with that curl command. Correct me if I'm wrong, but I don't think you can but html in a curl command. I'm just having the issue when downloading the spotify plugin I get: `Invalid Signature: blob`. i tried installing the spotify plugin through other means, but nothing is fixing it. The problem I'm having only gets close to problems clementine had with the spotify plugin **five years a go.** I wanted to open another issue, but I wasn't sure if this was something that had been solved or not.

**Comment by jbroadus** [comment]
Yeah, it was fixed, but looks like something changed again.
