### ISSUE TITLE
What do the extras do? What is "Rain" and "Make it so!"?

### ISSUE THREAD

**Issue by SystemParadox** [clementine-player/Clementine#6729]
Quick question, but I couldn't find any more information anywhere - what do the items in the "extras" menu do? I've got "Rain" and "Make it so!", but they don't seem to do anything? What are these?

**Comment by fitojb** [comment]
They’re sound effects that are supposed to play in the background while listening to music.

**Comment by jbroadus** [comment]
Rain was broken last time I checked.
https://github.com/clementine-player/Clementine/issues/6611

Make it so is supposed to sound like the bridge of the enterprise, but I think the gstreamer filters have changed since implementation and it's inaudible to me. https://github.com/clementine-player/Clementine/issues/2527

**Comment by foss-** [comment]
What is the point of maintaining such extras, when there is so much else related to music that needs work? Hypnotoad extra works. But is it really funny? It's a loud tone making it impossible to listen to music. Might have been fun at the time it was added and thers is probably an awesome backstory. But it feels wrong and if the audio is high it can actually be very disturbing to users.

**Comment by CristianNieto** [comment]
I liked the rain effect. 6 AM, Jazz, a cup of coffee with the rain effect makes a really great ambiance.

**Comment by SystemParadox** [comment]
They appear to work in 1.4.0rc1-280-gcf279e6f4.
